create table advertisements (type varchar(31) not null, id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, duration integer not null, end_date datetime, priority integer not null, start_date datetime not null, source_url varchar(1024) not null, text varchar(500), campaign_id bigint not null, segment_id bigint, primary key (id))
create table answers (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, label varchar(100) not null, value integer not null, question_id bigint not null, primary key (id))
create table audits (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, entity varchar(50) not null, entity_id bigint not null, new_value varchar(500) not null, old_value varchar(500) not null, primary key (id))
create table brands (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, background_image_url varchar(250) not null, cobrand varchar(500) not null, logo_image_url varchar(250) not null, primary key (id))
create table campaigns (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, defaulted bit not null, landing_url varchar(1024) not null, primary key (id))
create table hotspots (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, router_id bigint not null, primary key (id))
create table profile_values (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, key_id varchar(255) not null, value varchar(255) not null, profile_id bigint, primary key (id))
create table profiles (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, login_source varchar(255) not null, username varchar(50) not null, primary key (id))
create table profiles_mac_address (profile_id bigint not null, mac_address varchar(255))
create table questions (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, label varchar(100) not null, is_open bit not null, type varchar(255) not null, primary key (id))
create table questions_properties (question_id bigint not null, properties varchar(255))
create table router_groups (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, brand_id bigint, campaign_id bigint, default_campaign_id bigint, term_and_condition_id bigint, primary key (id))
create table router_groups_buttons (group_id bigint not null, button integer)
create table router_groups_questions (group_id bigint not null, question_id bigint not null, primary key (group_id, question_id))
create table routers (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, ip_v4_address varchar(15) not null, latitude double precision not null, location varchar(500) not null, longitude double precision not null, mac_address varchar(17) not null, group_id bigint not null, primary key (id))
create table segment_items (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, operator varchar(255) not null, value varchar(255) not null, question_id bigint, segment_id bigint not null, primary key (id))
create table segments (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, primary key (id))
create table service_terms (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, description varchar(500), name varchar(50) not null, text varchar(255) not null, primary key (id))
create table users (id bigint not null auto_increment, lock_version bigint, created_by varchar(50), created_date datetime, enabled bit not null, last_modified_by varchar(50), last_modified_date datetime, first_name varchar(50) not null, last_name varchar(50), middle_name varchar(50), observations varchar(1000), password_hash varchar(256), role varchar(255) not null, username varchar(50) not null, primary key (id))
alter table advertisements add constraint UK_jk6xe6ny24vc0xecarxlrm86o unique (name)
alter table answers add constraint UK_qm3m3aim8bho5mm1m1oath49l unique (name)
alter table brands add constraint UK_oce3937d2f4mpfqrycbr0l93m unique (name)
alter table campaigns add constraint UK_5rhrd2ghk2m15qnrfc7xyv81i unique (name)
alter table hotspots add constraint UK_74jlr28htjw6mlueh991e74m2 unique (name)
alter table profiles add constraint UK_gkg1kpmjy7f1hm6ugsoxmgisq unique (username)
alter table questions add constraint UK_3m8axyltkpnj3npycb5gd7tco unique (name)
alter table router_groups add constraint UK_8uwy1uoeajj8tyxfmao069du9 unique (name)
alter table routers add constraint UK_r3ggy8jgfei5b45yxqfveptda unique (name)
alter table routers add constraint UK_2eayn214k04xxquxqiuckq3bb unique (ip_v4_address)
alter table routers add constraint UK_kqlohpetvl2bs9qirsgg6jtui unique (mac_address)
alter table segments add constraint UK_6ccdgs7owwrk0ttbhjwj6yx9t unique (name)
alter table service_terms add constraint UK_luhpbobgnv8wa9qv9liw2c0gs unique (name)
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username)
alter table advertisements add constraint FKlenl8sxvnrwu2h1o96doyau6v foreign key (campaign_id) references campaigns (id)
alter table advertisements add constraint FK7hb0qn70e2yttux4pudrvgy0s foreign key (segment_id) references segments (id)
alter table answers add constraint FK3erw1a3t0r78st8ty27x6v3g1 foreign key (question_id) references questions (id)
alter table hotspots add constraint FKau7mtunw4v5fvub2tdkla9d16 foreign key (router_id) references routers (id)
alter table profile_values add constraint FKriljrdi7fucq33enjs855prjo foreign key (profile_id) references profiles (id)
alter table profiles_mac_address add constraint FKme2nkuxsce705ow68b3m5nvfb foreign key (profile_id) references profiles (id)
alter table questions_properties add constraint FKslraddkf6app1qy8scpsuvmrf foreign key (question_id) references questions (id)
alter table router_groups add constraint FK29pcglpjdbfhe5byril81mwqu foreign key (brand_id) references brands (id)
alter table router_groups add constraint FKr1slr5dplvmk1bbobbmvoeov4 foreign key (campaign_id) references campaigns (id)
alter table router_groups add constraint FK3k8wjdcmjfvcg59osf5lql0xt foreign key (default_campaign_id) references campaigns (id)
alter table router_groups add constraint FK6vj1yrg6tb5n4wusaa4jp1psq foreign key (term_and_condition_id) references service_terms (id)
alter table router_groups_buttons add constraint FKqtjtwkhkhjieqqmfwv7oqe7td foreign key (group_id) references router_groups (id)
alter table router_groups_questions add constraint FK37ocl278lnoafmxkw0a06ccl foreign key (question_id) references questions (id)
alter table router_groups_questions add constraint FKcp1ph2lyioj4g15d49qvoqiig foreign key (group_id) references router_groups (id)
alter table routers add constraint FKlu28mkqiemdaolcnygf1elqtd foreign key (group_id) references router_groups (id)
alter table segment_items add constraint FK27qolw0ygkxbq4i1617iun680 foreign key (question_id) references questions (id)
alter table segment_items add constraint FKjls6b9tkw6xyu82d75ixlohfd foreign key (segment_id) references segments (id)
